{% set name = "simplification" %}
{% set version = "0.7.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simplification-{{ version }}.tar.gz
    sha256: 4fbecf738eb36b6fe27c62824eb1c4d4f2700b56375e492fe67c1095747d07d3
  - git_url: https://github.com/urschrei/rdp.git
    git_rev: 525211da258e4864bcd3179e561d0e3dcb8dc60d
    folder: src/{{ name }}/rdp

build:
  skip: true  # [py<=37]
  number: 0
  missing_dso_whitelist:  # [win]
    - "*/rdp.dll"  # [win]

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - numpy
    - cython >=0.29.0
    - wheel >=0.29.0
    - pip
  run:
    - python

test:
  imports:
    - simplification
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Fast linestring simplification using RDP or Visvalingam-Whyatt and a Rust binary
  home: https://github.com/urschrei/simplification
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - urschrei
    - cheginit
